spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: customer-service
            uri: http://localhost:8881
            predicates:
              - Path=/customers/**
          - id: order-service
            uri: http://localhost:8883
            predicates:
              - Path=/orders/**
    discovery:
      enabled: true
server:
  port: 8888

